### ISSUE TITLE
Startup error reported in Node 14

### ISSUE THREAD

**Issue by Cphayim** [vrn-deco/cli#6]
System: macOS 12.2.1 
Node: 14.13.1 (Lowest Requirement)

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/promises
    at new NodeError (internal/errors.js:322:7)
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:63:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 2)
    at async link (internal/modules/esm/module_job.js:83:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
```

**Comment by titushartm** [comment]
Getting the same error on my git actions deployment workflow. Any idea what I can do there?
